console.log("In this file we are practice for how to check data type in over variable ");
let a = "my_name";
let b = 20;
let c = true;
let d = null;
let e = "";
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
console.log(typeof d);
console.log(typeof e);
console.log("in this file we are cheking over data type");
